# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fleetv3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fleetv3
  pod 'Stripe'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'
  pod 'SwiftyJSON', :git => 'https://github.com/BaiduHiDeviOS/SwiftyJSON.git', :branch => 'swift3'

  target 'Fleetv3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Fleetv3UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
